### ISSUE TITLE
`trace.span` spams logs with the same repeated message in case of an error bubbling up

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/ray-on-golem#191]
See:

```
Getting allocation failed with `Insufficient funds to make allocation. Top up your account or release all existing allocations to unlock the funds via `yagna payment release-allocations``
```

in the following logfile:

[webserver_debug.log.1.log](https://github.com/golemfactory/ray-on-golem/files/14376406/webserver_debug.log.1.log)

**Comment by shadeofblue** [comment]
[webserver_debug.log.1.log](https://github.com/golemfactory/ray-on-golem/files/14376406/webserver_debug.log.1.log)

**Comment by mateuszsrebrny** [comment]
These are debug logs, at top level it is an ERROR, agreement and draft levels are INFO.
Let's leave as it is.
