### ISSUE TITLE
yagna version conflict when installing ray-on-golem

### ISSUE THREAD

**Issue by krunch3r76** [golemfactory/ray-on-golem#260]
### Bug Report: yagna version conflict when installing ray-on-golem

**Version:** 0.12.1  
**Environment:** Ubuntu 20.04
**Affected Executable:** `<environment>/bin/yagna`

**Problem Description:**

Installing the `ray-on-golem` pip package in a clean virtual environment installs an outdated version of `yagna` (0.12.1) to the path, causing both `yagna` and `ray-on-golem` to fail to start.

Currently, the `ray-on-golem` package installs and runs `yagna` version 0.15.2, which crashes with the following error:

```
Caused by:
    VersionMissing(20240301000000)
[2024-08-29T17:43:24.985-0700 INFO  ya_service_bus::connection] stopped connection to gsb
Error: VersionMissing(20240301000000), /home/runner/.cargo/git/checkouts/erc20_payment_lib-fffa785e9cf776f9/0304f7f/crates/erc20_payment_lib_common/src/db/connection.rs:57:43
```
Running `yagna` 0.16.0 (the most recent version) in a separate process prevents this crash, indicating that the issue is related to the older `yagna` version being installed.

**Steps to Reproduce:**
- *Follow the [quickstart tutorial](https://docs.golem.network/docs/quickstarts/ray-quickstart#quickstart-2) or use the steps below:*

1. Set up a clean virtual environment.
2. Install the `ray-on-golem` package using pip.
3. Download `golem-cluster.yaml`.
4. Attempt to start ray-on-golem via `**ray up golem-cluster.yaml --yes**` and observe the crash.

**Proposed Solution:**

Please consider releasing a patch for `ray-on-golem` that updates `yagna` to the latest stable version (0.16.0) to prevent this issue.

**Attachments:**
![webserver_failure](https://github.com/user-attachments/assets/0f9f44f9-7e00-4529-8ce2-c877a9e341e7)
[yagna.log](https://github.com/user-attachments/files/16808923/yagna.log)
[webserver_debug.log](https://github.com/user-attachments/files/16808930/webserver_debug.log)

Thank you for your attention to this matter.

**Comment by krunch3r76** [comment]
i am closing the issue because on a clean install even despite the version differences, this issue is not reproducible (as by the steps listed).

**Comment by mateuszsrebrny** [comment]
The issue was that `ray-on-golem` was installing `yagna` 0.15. It is easily upgradable to `yagna` 0.16, but not the other way around. So, when you already had `yagna` 0.16, `ray-on-golem` pulled 0.15 and couldn't use the datadir.

Since `ray-on-golem` 0.13.0 `yagna` 0.16 is used :)
